### ISSUE TITLE
Not compatible with Node 6

### ISSUE THREAD

**Issue by niederlec** [Inist-CNRS/text-quality-indicator#8]
Due to the usage of Nodehun, text-quality-indicator is not compatible with Node v6
https://github.com/nathanjsweet/nodehun/issues/31

**Comment by niederlec** [comment]
Great Warning : "Nodehun is no longer being actively maintained. Please email nathanjsweet@gmail.com If you are interested in taking over the project."

**Comment by rmeja** [comment]
Thank you for the information (we know already :wink: ). We know what we have to do: take the Nodehun's maintenance to make it compatible with Node v6.
